name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.X"
    - name: Install dependencies
      run: |
        python -m pip install tox
    - name: Test with tox
      run: |
        tox

  verify-apps:
    name: Build App
    needs: unit-tests
    uses: beeware/.github/.github/workflows/app-build-verify.yml@main
    with:
      python-version: "3.9"
      briefcase-template-source: "../../"
      runner-os: ${{ matrix.runner-os }}
      framework: ${{ matrix.framework }}
    strategy:
      fail-fast: false
      matrix:
        framework: [ "toga", "pyside2", "pyside6", "ppb" ]
        runner-os: [ "macos-latest", "ubuntu-latest", "windows-latest" ]
